[package]
name = "rust-lib"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["staticlib"]
path = "lib.rs"

[dependencies]
ocaml = { version = "0.22.0" }

[build]
# this is required for MacOS
rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup"]
